services:
  backend:
    build: .
    environment:
      - POSTGRES_CONNECTION_URL=${POSTGRES_CONNECTION_URL}
      - LOGGING_FOLDER=${LOGGING_FOLDER}
      - LOG_FILE=${LOG_FILE}
    ports:
      - "3003:3003"
