Table student {
  id int [pk]
  name varchar [not null]
  teacher_id int [not null]
}

Table teacher {
  id int [pk]
  name varchar [not null]
}

Table course_record {
  id int [pk]
  student_id int [not null]
  start_date timestamp [not null] // basically what helps you to track the semester count
  grade float 
  gpa float
}

Ref: student.id < course_record.student_id
Ref: teacher.id - student.teacher_id