Table student {
  id int [pk]
  name varchar [not null]
}

Table teacher {
  id int [pk]
  name varchar [not null]
}

Table course_record {
  id int [pk]
  student_id int
  teacher_id int 
  start_date timestamp // basically what helps you to track the semester count
  grade float 
  gpa float
}

Ref: student.id < course_record.student_id
Ref: teacher.id < course_record.teacher_id